linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - asciicheck
    - containedctx
    - contextcheck
    - errchkjson
    - errorlint
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecknoglobals
    - gofmt
    - gosec
    - makezero
    - nilerr
    - nilnil
    - predeclared
    - reassign
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
