env:
  - CGO_ENABLED=0

builds:
  - id: armaria-darwin-amd64
    binary: armaria
    main: ./cmd/cli
    goarch:
      - amd64
    goos:
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X "main.version={{ .Version }}"

  - id: armaria-darwin-arm64
    binary: armria
    main: ./cmd/cli
    goarch:
      - arm64
    goos:
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X "main.version={{ .Version }}"

  - id: armaria-linux-amd64
    binary: armaria
    main: ./cmd/cli
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X "main.version={{ .Version }}"

  - id: armaria-windows-amd64
    binary: armaria
    main: ./cmd/cli
    goarch:
      - amd64
    goos:
      - windows
    flags:
      - -trimpath
      - -buildmode=exe
    ldflags:
      - -s
      - -w
      - -X "main.version={{ .Version }}"

universal_binaries:
  - id: armaria-darwin-universal
    ids:
      - armaria-darwin-amd64
      - armaria-darwin-arm64
    replace: true
    name_template: "armaria"

archives:
  - id: armaria-linux-archive
    builds:
      - armaria-linux-amd64
    name_template: "armaria_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: zip
    files:
      - none*
  - id: armaria-windows-archive
    builds:
      - armaria-windows-amd64
    name_template: "armaria_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: zip
    files:
      - none*
  - id: armaria-macos-archive
    builds:
      - armaria-darwin-universal
    name_template: "armaria_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: zip
    files:
      - none*

upx:
  - enabled: true
    goos: [linux, windows] # UPX doesn't work for MacOS ATM
    compress: best

checksum:
  name_template: 'checksums.txt'

gomod:
  proxy: true

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc

sboms:
  - artifacts: archive

release:
  extra_files:
    - glob: ./**/*.snap

snapcrafts:
  - id: armaria-snap
    builds:
      - armaria-linux-amd64
    name_template: "armaria_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    name: armaria
    title: Armaria
    publish: true
    summary: Armaria is a fast, open, and local first bookmarks manager.
    description: Armaria is a FOSS bookmarks manager that keeps all of your local bookmarks in a SQLite database. You can use many different frontends to manage your bookmarks including browsers, and back them up and/or sync them however you see fit.
    confinement: strict
    license: MIT
    base: core18
    extra_files:
      - source: ./art/cabinet-light-128.png
        destination: meta/gui/icon.png
        mode: 0755
    apps:
      armaria:  
        command: armaria
        plugs: ["dot-mozilla-native-messaging-hosts", "dot-config-google-chrome-native-messaging-hosts", "dot-config-chromium-native-messaging-hosts"]
    plugs:
      dot-mozilla-native-messaging-hosts:
        interface: personal-files
        write:
          - $HOME/.mozilla/native-messaging-hosts
      dot-config-google-chrome-native-messaging-hosts:
        interface: personal-files
        write:
          - $HOME/.config/google-chrome/NativeMessagingHosts
      dot-config-chromium-native-messaging-hosts:
        interface: personal-files
        write:
          - $HOME/.config/chromium/NativeMessagingHosts

winget:
  - name: Armaria
    publisher: Jonathan Hope
    short_description: Armaria is a fast, open, and local first bookmarks manager.
    license: "mit"
    publisher_url: https://github.com/JonathanHope/armaria
    publisher_support_url: https://github.com/JonathanHope/armaria/issues/new
    package_identifier: Armaria.Armaria
    ids:
      - armaria-windows-archive
    url_template: "https://github.com/JonathanHope/armaria/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    path: manifests/a/Armaria/Armaria/{{ .Version }}
    commit_msg_template: "{{ .PackageIdentifier }}: {{ .Version }}"
    homepage: https://github.com/JonathanHope/armaria
    description: Armaria is a FOSS bookmarks manager that keeps all of your local bookmarks in a SQLite database. You can use many different frontends to manage your bookmarks including browsers, and back them up and/or sync them however you see fit.
    license_url: https://github.com/JonathanHope/armaria/blob/main/LICENSE
    copyright: Jonathan Hope
    release_notes: "{{.Changelog}}"
    release_notes_url: "https://github.com/JonathanHope/armaria/releases/tag/{{ .Tag }}"
    tags:
      - bookmarks
    commit_author:  
      name: Jonathan Hope
      email: jhope@fastmail.com
    repository:
      owner: JonathanHope
      name: winget-pkgs
      branch: "{{.ProjectName}}-{{.Version}}"
      token: "{{ .Env.WINGET_AUTH_TOKEN }}"

brews:
  - name: armaria
    ids:
    - armaria-macos-archive
    url_template: "https://github.com/JonathanHope/armaria/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: Jonathan Hope
      email: jhope@fastmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/JonathanHope/armaria"
    description: Armaria is a fast, open, and local first bookmarks manager.
    license: "MIT"
    repository:
      owner: JonathanHope
      name: homebrew-armaria
      branch: main
      token: "{{ .Env.TAP_AUTH_TOKEN }}"

nix:
  - name: armaria
    ids:
      - armaria-linux-archive
    url_template: "https://github.com/JonathanHope/armaria/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:  
      name: Jonathan Hope
      email: jhope@fastmail.com
    commit_msg_template: "{{ .ProjectName }}: {{ .Tag }}"
    homepage: https://github.com/JonathanHope/armaria
    description: Armaria is a fast, open, and local first bookmarks manager.
    license: "mit"
    repository:
      owner: JonathanHope
      name: nur-armaria
      branch: master
      token: "{{ .Env.NUR_AUTH_TOKEN }}"
