* Armaria

#+BEGIN_QUOTE
Armaria are a kind of closed, labeled cupboards that were used for book storage in ancient times up till the middle ages.
#+END_QUOTE

*NOTE: This software is still in progress and should be considered pre alpha*

Armaria is a new way to manage your bookmarks.

As it stands bookmarks are stored either in the cloud, in browser specific formats, or both. It doesn't have to be this way. Armaria stores bookmarks in a SQLite database. This means your bookmarks are local and shared across all clients including browsers.

* Supported Platforms

 - Windows x64
 - Linux x64
 - Mac x64/arm64

* Features

 - URL, Name, and Description fields
 - Nested folder structure
 - Tags
 - Full text search
 - CLI

* Schema

The ERD for the bookmarks database is as follows:

#+begin_src mermaid :file "bookmarks-db.svg" :pupeteer-config-file "~/.emacs.d/pupeteer-config.json" :mermaid-config-file "~/.emacs.d/mermaid-config.json" :background-color "transparent"
erDiagram
  bookmarks ||--|{ bookmarks_tags: ""
  tags ||--|{ bookmarks_tags: ""
  bookmarks o|--o{ bookmarks: ""
  
  bookmarks {
    text id
    text parent_id
    integer is_folder
    text name
    text url
    text description
    text modified
  }

  tags {
    text tag
    text modified
  }

  bookmarks_tags {
    text bookmark_id
    text tag
    text modified
  }
#+end_src

#+RESULTS:
[[file:bookmarks-db.svg]]

 
* FAQ

** How do I back up my bookmarks?

You can use whatever you are already using to backup your files to the cloud.
