version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint run --config .golangci.yml --timeout 3m
  test-internal:
    dir: internal
    cmds:
      - go test -count=1 ./... 
  test-cmd:
    dir: cmd
    cmds:
      - go test -count=1 --tags "fts5" ./...
  test:
    cmds:
      - task: test-internal
      - task : test-cmd
  build-cli:
    dir: cmd/cli
    cmds:
      - go build --tags "fts5" -ldflags="-X main.version=local"
      - cp cli ../../armaria
  build-host:
    dir: cmd/host
    cmds:
      - go build --tags "fts5"
      - cp host ../../armaria-host
  build-seeder:
    dir: cmd/seeder
    cmds:
      - go build --tags "fts5"
      - cp seeder ../../armaria-seeder
  build:
    cmds:
      - task: build-cli
      - task: build-host
      - task: build-seeder
  migrate-up:
    cmds:
      - goose -dir ./internal/db/migrations sqlite3 ./bookmarks.db up
  migrate-down:
    cmds:
      - goose -dir ./internal/db/migrations sqlite3 ./bookmarks.db down
  clean:
    cmds:
      - rm -f armaria
      - rm -f armaria-host
      - rm -f armaria-seeder
      - rm -f cmd/cli/cli
      - rm -f cmd/host/host
      - rm -f cmd/seeder/seeder
      - find . -name "*.db" -type f -delete
      - find . -name "*.db-shm" -type f -delete
      - find . -name "*.db-wal" -type f -delete
  vulns:
    cmds:
      - ./tools/snyk
  release:
    cmds:
      - goreleaser release
  release-snapshot:
    cmds:
      - goreleaser release --snapshot --clean
