name: Build, Test and Lint Armaria

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v22
      - name: Build
        run: task build
        shell: nix develop --command bash -e {0}
      - name: Test
        run: task test
        shell: nix develop --command bash -e {0}
      - name: Lint
        run: task lint
        shell: nix develop --command bash -e {0}
