name: Build, Test and Lint Armaria

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  lint:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
      - name: Setup golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.1
      - name: Build
        run: task build
      - name: Test
        run: task test
      - name: Lint
        run: task lint
