name: Release Armaria

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v22
      - name: Setup Docker
        run: |
          brew install docker
          brew install colima
          colima start
      - name: Release
        run: |
          export SDK=$(xcrun --sdk macosx --show-sdk-path)
          echo $SDK
          task release
        shell: nix develop --command bash -e {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WINGET_AUTH_TOKEN: ${{ secrets.WINGET_AUTH_TOKEN }}
          TAP_AUTH_TOKEN: ${{ secrets.TAP_AUTH_TOKEN }}
          NUR_AUTH_TOKEN: ${{ secrets.NUR_AUTH_TOKEN }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
          SDK: 
